# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/priyapatel/sp22/cs402/Noisey-image/src/qt_designer_file/dialogAug.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 477)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 430, 591, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(20, 50, 256, 251))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 32, 111, 20))
        self.label_2.setObjectName("label_2")
        self.noiseRange = QtWidgets.QLineEdit(Dialog)
        self.noiseRange.setGeometry(QtCore.QRect(300, 276, 161, 25))
        self.noiseRange.setObjectName("noiseRange")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(301, 256, 161, 17))
        self.label_3.setObjectName("label_3")
        self.previewImage = QtWidgets.QLabel(Dialog)
        self.previewImage.setGeometry(QtCore.QRect(300, 50, 321, 181))
        self.previewImage.setText("")
        self.previewImage.setObjectName("previewImage")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(480, 257, 91, 17))
        self.label_5.setObjectName("label_5")
        self.exampleLine = QtWidgets.QLineEdit(Dialog)
        self.exampleLine.setGeometry(QtCore.QRect(479, 276, 91, 25))
        self.exampleLine.setObjectName("exampleLine")
        self.info_label = QtWidgets.QLabel(Dialog)
        self.info_label.setGeometry(QtCore.QRect(30, 320, 591, 101))
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Augmentations:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Preview:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Noise (or Noise Range)"))
        self.label_5.setText(_translate("Dialog", "Example:"))
